name: Add Issue to Project on Creation

on:
  issues:
    types:
      - opened

jobs:
  add-to-kanban:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "PVT_kwDODB6w4M4A0YLS"  # ID del Proyecto
      FIELD_STATUS_ID: "PVTSSF_lADODB6w4M4A0YLSzgqBSYE"  # ID del campo "Status"
      STATUS_BACKLOG_ID: "8af699e8"  # ID del estado "Backlog" o "To Do"

    steps:
      - name: Obtener ID del Issue
        id: get-issue-id
        run: |
          ISSUE_ID="${{ github.event.issue.node_id }}"

          if [ -z "$ISSUE_ID" ]; then
            echo "❌ No se pudo obtener el ID del Issue. Saliendo..."
            exit 1
          fi

          echo "✅ ID del Issue obtenido: $ISSUE_ID"
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Agregar el Issue al Proyecto
        id: add-to-project
        run: |
          PROJECT_ITEM_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { addProjectV2ItemById(input: { projectId: \"'$PROJECT_ID'\", contentId: \"'$ISSUE_ID'\" }) { item { id } } }" }' | jq -r '.data.addProjectV2ItemById.item.id')

          if [ "$PROJECT_ITEM_ID" == "null" ]; then
            echo "❌ No se pudo agregar el Issue al Proyecto. Saliendo..."
            exit 1
          fi

          echo "✅ Issue agregado al Proyecto con ID: $PROJECT_ITEM_ID"
          echo "PROJECT_ITEM_ID=$PROJECT_ITEM_ID" >> $GITHUB_ENV

      - name: Asignar Estado Inicial ("Backlog" o "To Do")
        run: |
          RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'$PROJECT_ID'\", itemId: \"'$PROJECT_ITEM_ID'\", fieldId: \"'$FIELD_STATUS_ID'\", value: { singleSelectOptionId: \"'$STATUS_BACKLOG_ID'\" } }) { projectV2Item { id } } }" }')

          if [[ "$RESPONSE" == *"errors"* ]]; then
            echo "❌ Error al asignar el estado inicial. Respuesta: $RESPONSE"
            exit 1
          fi

          echo "✅ Estado inicial asignado correctamente."
