name: Move Issue to To Do when assigned

on:
  issues:
    types:
      - assigned

jobs:
  move-to-do:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "PVT_kwDODB6w4M4A0YLS"
      FIELD_STATUS_ID: "PVTSSF_lADODB6w4M4A0YLSzgqBSYE"
      STATUS_TODO_ID: "f75ad846"

    steps:
      - name: Mover Issue a "To Do"
        run: |
          ISSUE_ID=${{ github.event.issue.node_id }}

          PROJECT_ITEM_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { addProjectV2ItemById(input: { projectId: \"'$PROJECT_ID'\", contentId: \"'$ISSUE_ID'\" }) { item { id } } }" }' | jq -r '.data.addProjectV2ItemById.item.id')

          curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'$PROJECT_ID'\", itemId: \"'$PROJECT_ITEM_ID'\", fieldId: \"'$FIELD_STATUS_ID'\", value: { singleSelectOptionId: \"'$STATUS_TODO_ID'\" } }) { projectV2Item { id } } }" }'
