name: Move Issue to To Do when assigned

on:
  issues:
    types:
      - assigned
  project_item:
    types:
      - edited  # Detecta cuando se asigna un responsable en el Kanban

jobs:
  move-to-do:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "PVT_kwDODB6w4M4A0YLS"
      FIELD_STATUS_ID: "PVTSSF_lADODB6w4M4A0YLSzgqBSYE"
      STATUS_TODO_ID: "f75ad846"

    steps:
      - name: Obtener el ID del Issue o Item en el Proyecto
        run: |
          if [[ -n "${{ github.event.issue.node_id }}" ]]; then
            ISSUE_ID=${{ github.event.issue.node_id }}
          else
            ISSUE_ID=${{ github.event.project_item.node_id }}
          fi
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Agregar el Issue al Proyecto (si no está agregado)
        run: |
          PROJECT_ITEM_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { addProjectV2ItemById(input: { projectId: \"'$PROJECT_ID'\", contentId: \"'$ISSUE_ID'\" }) { item { id } } }" }' | jq -r '.data.addProjectV2ItemById.item.id')

          echo "PROJECT_ITEM_ID=$PROJECT_ITEM_ID" >> $GITHUB_ENV

      - name: Mover el Issue a "To Do"
        run: |
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'$PROJECT_ID'\", itemId: \"'$PROJECT_ITEM_ID'\", fieldId: \"'$FIELD_STATUS_ID'\", value: { singleSelectOptionId: \"'$STATUS_TODO_ID'\" } }) { projectV2Item { id } } }" }'
