name: Move Issue to To Do when assigned

on:
  issues:
    types:
      - assigned

jobs:
  move-to-do:
    runs-on: ubuntu-latest
    steps:
      - name: Mover a "To Do" en el GitHub Project
        run: |
          ISSUE_ID=${{ github.event.issue.node_id }}
          PROJECT_ID="1"  # Cambia esto con tu ID del proyecto
          COLUMN_ID="2"  # Cambia esto con el ID de la columna "To Do"

          curl -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/${COLUMN_ID}/cards \
            -d "{\"content_id\": \"${ISSUE_ID}\", \"content_type\": \"Issue\"}"
