name: Move Issue to Done when manually closed

on:
  issues:
    types:
      - closed

jobs:
  move-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Mover a "Done"
        run: |
          ISSUE_ID=${{ github.event.issue.node_id }}
          COLUMN_ID="4"  # Reemplázalo con el ID de la columna "Done"

          curl -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/${COLUMN_ID}/cards \
            -d "{\"content_id\": \"${ISSUE_ID}\", \"content_type\": \"Issue\"}"
