name: Move Issue to Done when manually closed

on:
  issues:
    types:
      - closed

jobs:
  move-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Mover a "Done"
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ secrets.KANBAN_URL }}
          github-token: ${{ secrets.PAT }}
          content-id: ${{ github.event.issue.node_id }}
          status: "Done"
