name: Move all Issues from Stage to Main when PR is merged

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Solo se ejecuta cuando un PR a main es mergeado

jobs:
  move-to-main:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "PVT_kwDODB6w4M4A0YLS"  # ID del Proyecto
      FIELD_STATUS_ID: "PVTSSF_lADODB6w4M4A0YLSzgqBSYE"  # ID del campo "Status"
      STATUS_STAGE_ID: "fbe3acd1"  # ID del estado "Stage"
      STATUS_MAIN_ID: "61c07dd7"  # ID del estado "Main"

    steps:
      - name: Obtener información del PR
        id: get-pr-info
        run: |
          PR_URL="${{ github.event.pull_request.url }}"
          PR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" -H "Accept: application/vnd.github.v3+json" $PR_URL)
          HEAD_BRANCH=$(echo "$PR_DATA" | jq -r '.head.ref')
          BASE_BRANCH=$(echo "$PR_DATA" | jq -r '.base.ref')

          echo "Base Branch (Destino del PR): $BASE_BRANCH"
          echo "Head Branch (Origen del PR): $HEAD_BRANCH"

          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

      - name: Verificar si el PR proviene de "stage"
        run: |
          if [ "${{ env.BASE_BRANCH }}" != "main" ]; then
            echo "❌ El PR no va hacia main. No debería haberse ejecutado este workflow. Saliendo..."
            exit 1
          fi

          if [ "${{ env.HEAD_BRANCH }}" != "stage" ]; then
            echo "❌ El PR no proviene de stage. No se moverán issues. Saliendo..."
            exit 0
          fi

      - name: Obtener todas las tareas en "Stage"
        id: get-stage-items
        run: |
          ITEMS=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "query { node(id: \"'$PROJECT_ID'\") { ... on ProjectV2 { items(first: 100) { nodes { id fieldValues(first: 10) { nodes { __typename ... on ProjectV2ItemFieldSingleSelectValue { optionId field { ... on ProjectV2FieldCommon { id } } } } } } } } } }" }' | jq -c '.data.node.items.nodes | map(select(.fieldValues.nodes | any(.optionId == "'$STATUS_STAGE_ID'")))')
          
          echo "ITEMS=$ITEMS" >> $GITHUB_ENV

      - name: Verificar si hay Issues en "Stage"
        run: |
          if [ -z "${{ env.ITEMS }}" ] || [ "${{ env.ITEMS }}" == "[]" ]; then
            echo "❌ No hay issues en Stage para mover. Saliendo..."
            exit 0
          fi

      - name: Mover todas las tareas de "Stage" a "Main"
        run: |
          for ITEM in $(echo '${{ env.ITEMS }}' | jq -r '.[].id'); do
            RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/graphql \
              -d '{ "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'$PROJECT_ID'\", itemId: \"'$ITEM'\", fieldId: \"'$FIELD_STATUS_ID'\", value: { singleSelectOptionId: \"'$STATUS_MAIN_ID'\" } }) { projectV2Item { id } } }" }')

            echo "✔️ Movido $ITEM de 'Stage' a 'Main': $RESPONSE"
          done
