name: Move Issue to In Progress when PR is opened

on:
  pull_request:
    types:
      - opened

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Extraer número de issue del PR
        id: extract-issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE "fix #([0-9]+)" | awk '{print $2}' | tr -d '#')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Obtener ID del Issue
        id: get-issue-id
        run: |
          ISSUE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }} | jq -r .node_id)
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Mover a "In Progress"
        run: |
          COLUMN_ID="3"  

          curl -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/${COLUMN_ID}/cards \
            -d "{\"content_id\": \"${{ env.ISSUE_ID }}\", \"content_type\": \"Issue\"}"
