name: Move Issue to In Progress when PR is opened

on:
  pull_request:
    types:
      - opened

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "PVT_kwDODB6w4M4A0YLS"  # ID del Proyecto
      FIELD_STATUS_ID: "PVTSSF_lADODB6w4M4A0YLSzgqBSYE"  # ID del campo "Status"
      STATUS_IN_PROGRESS_ID: "47fc9ee4"  # ID del estado "In Progress"

    steps:
      - name: Extraer número de Issue del PR
        id: extract-issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.title }}" | grep -oE "fix #([0-9]+)" | awk '{print $2}' | tr -d '#')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Verificar si el número de Issue fue detectado
        run: |
          if [ -z "${{ env.ISSUE_NUMBER }}" ]; then
            echo "❌ No se encontró un número de Issue en el PR. Saliendo..."
            exit 1
          fi

      - name: Obtener el ID del Issue desde GitHub API
        id: get-issue-id
        run: |
          ISSUE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }} | jq -r .node_id)
          
          if [ "$ISSUE_ID" == "null" ]; then
            echo "❌ No se pudo obtener el node_id del Issue. Saliendo..."
            exit 1
          fi

          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Agregar el Issue al Proyecto (si no está agregado)
        id: add-to-project
        run: |
          PROJECT_ITEM_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { addProjectV2ItemById(input: { projectId: \"'$PROJECT_ID'\", contentId: \"'$ISSUE_ID'\" }) { item { id } } }" }' | jq -r '.data.addProjectV2ItemById.item.id')

          if [ "$PROJECT_ITEM_ID" == "null" ]; then
            echo "❌ No se pudo agregar el Issue al Proyecto. Saliendo..."
            exit 1
          fi

          echo "PROJECT_ITEM_ID=$PROJECT_ITEM_ID" >> $GITHUB_ENV

      - name: Mover el Issue a "In Progress"
        run: |
          RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ALNACKLO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{ "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'$PROJECT_ID'\", itemId: \"'$PROJECT_ITEM_ID'\", fieldId: \"'$FIELD_STATUS_ID'\", value: { singleSelectOptionId: \"'$STATUS_IN_PROGRESS_ID'\" } }) { projectV2Item { id } } }" }')

          if [[ "$RESPONSE" == *"errors"* ]]; then
            echo "❌ Error al mover el Issue a 'In Progress'. Respuesta: $RESPONSE"
            exit 1
          fi

          echo "✅ Issue movido a 'In Progress' correctamente."
